server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
uri: http://127.0.0.1:8080/user
predicates:
  - Path=/**
